/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.sistemaResumido;

import ventanas.sistemaNuevo.*;
import ventanas.demo.*;

/**
 *
 * @author jacqu
 */
public class VentanaPrincipalSistemaResumido extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(VentanaPrincipalSistemaResumido.class.getName());

    /**
     * Creates new form VentanaDemoSistema
     */
    public VentanaPrincipalSistemaResumido() {
        initComponents();
        setTitle("ERP - Sistema con Datos Precargados");
        setLocationRelativeTo(null);

        // F1: autores
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0), "mostrarAutores");
        getRootPane().getActionMap().put("mostrarAutores", new javax.swing.AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                new ventanas.VentanaIntegrantes().setVisible(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        bmnAreas = new javax.swing.JMenu();
        imnAltaAreas = new javax.swing.JMenuItem();
        imnBajaAreas = new javax.swing.JMenuItem();
        imnModificacionAreas = new javax.swing.JMenuItem();
        imnMovimientoAreas = new javax.swing.JMenuItem();
        bmnManagers = new javax.swing.JMenu();
        imnAltaManagers = new javax.swing.JMenuItem();
        imnBajaManagers = new javax.swing.JMenuItem();
        imnModificacionManagers = new javax.swing.JMenuItem();
        bmnEmpleados = new javax.swing.JMenu();
        imnAltaEmpleados = new javax.swing.JMenuItem();
        bmnReportes = new javax.swing.JMenu();
        imnReporteInteligente = new javax.swing.JMenuItem();
        imnReporteEstadoAreas = new javax.swing.JMenuItem();
        imnReporteMovimientos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ERP Empresarial");
        setName("VentanaPrincipal"); // NOI18N

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
                pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 427, Short.MAX_VALUE));
        pnlPrincipalLayout.setVerticalGroup(
                pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 331, Short.MAX_VALUE));

        bmnAreas.setText("Areas");

        imnAltaAreas.setText("Alta");
        bmnAreas.add(imnAltaAreas);

        imnBajaAreas.setText("Baja");
        imnBajaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnBajaAreasActionPerformed(evt);
            }
        });
        bmnAreas.add(imnBajaAreas);

        imnModificacionAreas.setText("Modificacion");
        imnModificacionAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnModificacionAreasActionPerformed(evt);
            }
        });
        bmnAreas.add(imnModificacionAreas);

        imnMovimientoAreas.setText("Realizar Movimiento");
        bmnAreas.add(imnMovimientoAreas);

        barraMenu.add(bmnAreas);

        bmnManagers.setText("Managers");

        imnAltaManagers.setText("Alta");
        bmnManagers.add(imnAltaManagers);

        imnBajaManagers.setText("Baja");
        imnBajaManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnBajaManagersActionPerformed(evt);
            }
        });
        bmnManagers.add(imnBajaManagers);

        imnModificacionManagers.setText("Modificacion");
        bmnManagers.add(imnModificacionManagers);

        barraMenu.add(bmnManagers);

        bmnEmpleados.setText("Empleados");

        imnAltaEmpleados.setText("Alta");
        bmnEmpleados.add(imnAltaEmpleados);

        barraMenu.add(bmnEmpleados);

        bmnReportes.setText("Reportes");

        imnReporteInteligente.setText("Reporte Inteligente");
        imnReporteInteligente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnReporteInteligenteActionPerformed(evt);
            }
        });
        bmnReportes.add(imnReporteInteligente);

        imnReporteEstadoAreas.setText("Reporte de Estado de Areas");
        bmnReportes.add(imnReporteEstadoAreas);

        imnReporteMovimientos.setText("Reporte de Movimientos");
        imnReporteMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnReporteMovimientosActionPerformed(evt);
            }
        });
        bmnReportes.add(imnReporteMovimientos);

        barraMenu.add(bmnReportes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imnBajaAreasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnBajaAreasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_imnBajaAreasActionPerformed

    private void imnModificacionAreasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnModificacionAreasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_imnModificacionAreasActionPerformed

    private void imnBajaManagersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnBajaManagersActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_imnBajaManagersActionPerformed

    private void imnReporteInteligenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnReporteInteligenteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_imnReporteInteligenteActionPerformed

    private void imnReporteMovimientosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnReporteMovimientosActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_imnReporteMovimientosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu bmnAreas;
    private javax.swing.JMenu bmnEmpleados;
    private javax.swing.JMenu bmnManagers;
    private javax.swing.JMenu bmnReportes;
    private javax.swing.JMenuItem imnAltaAreas;
    private javax.swing.JMenuItem imnAltaEmpleados;
    private javax.swing.JMenuItem imnAltaManagers;
    private javax.swing.JMenuItem imnBajaAreas;
    private javax.swing.JMenuItem imnBajaManagers;
    private javax.swing.JMenuItem imnModificacionAreas;
    private javax.swing.JMenuItem imnModificacionManagers;
    private javax.swing.JMenuItem imnMovimientoAreas;
    private javax.swing.JMenuItem imnReporteEstadoAreas;
    private javax.swing.JMenuItem imnReporteInteligente;
    private javax.swing.JMenuItem imnReporteMovimientos;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
