/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.sistemaNuevo;

import ventanas.demo.*;
import logica.Sistema;
import java.util.ArrayList;
import modelo.Area;
import modelo.Manager;
import modelo.Manager;
import modelo.Area;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import modelo.Empleado;

/**
 *
 * @author jacqu
 */
public class VentanaPrincipalSistemaNuevo extends javax.swing.JFrame {

    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(VentanaPrincipalSistemaNuevo.class.getName());

    // --- Listado y detalle de empleados ---
    private JList<String> lstEmpleados;
    private DefaultListModel<String> modeloListaEmpleados;
    private java.util.ArrayList<Empleado> cacheOrdenado; // referencia a los empleados mostrados

    // Panel de detalle
    private JLabel lblNombre;
    private JLabel lblCI;
    private JLabel lblCelular;
    private JLabel lblSalario;
    private JLabel lblManager;
    private JLabel lblArea;
    private JLabel lblRutaCV;

    public VentanaPrincipalSistemaNuevo() {
        this(new Sistema());
    }

    public VentanaPrincipalSistemaNuevo(Sistema sistema) {
        this.sistema = sistema;

        initComponents();
        setTitle("ERP - Sistema Nuevo");
        setLocationRelativeTo(null);
        initUIListadoEmpleados();
        refrescarListaEmpleados();

        // F1: autores
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0), "mostrarAutores");
        getRootPane().getActionMap().put("mostrarAutores", new javax.swing.AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                new ventanas.VentanaIntegrantes().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();

        bmnAreas = new javax.swing.JMenu();
        imnAltaAreas = new javax.swing.JMenuItem();
        imnBajaAreas = new javax.swing.JMenuItem();
        imnModificacionAreas = new javax.swing.JMenuItem();
        imnMovimientoAreas = new javax.swing.JMenuItem();

        bmnManagers = new javax.swing.JMenu();
        imnAltaManagers = new javax.swing.JMenuItem();
        imnBajaManagers = new javax.swing.JMenuItem();
        imnModificacionManagers = new javax.swing.JMenuItem();

        bmnEmpleados = new javax.swing.JMenu();
        imnAltaEmpleados = new javax.swing.JMenuItem();

        bmnReportes = new javax.swing.JMenu();
        imnReporteInteligente = new javax.swing.JMenuItem();
        imnReporteEstadoAreas = new javax.swing.JMenuItem();
        imnReporteMovimientos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ERP Empresarial");
        setName("VentanaPrincipal"); // NOI18N

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
                pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 427, Short.MAX_VALUE));
        pnlPrincipalLayout.setVerticalGroup(
                pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 331, Short.MAX_VALUE));

        bmnAreas.setText("Areas");

        imnAltaAreas.setText("Alta");
        bmnAreas.add(imnAltaAreas);
        imnAltaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Diálogo simple con 3 campos
                javax.swing.JTextField txtNombre = new javax.swing.JTextField();
                javax.swing.JTextField txtDesc = new javax.swing.JTextField();
                javax.swing.JTextField txtPres = new javax.swing.JTextField();

                Object[] msg = {
                        "Nombre:", txtNombre,
                        "Descripción:", txtDesc,
                        "Presupuesto anual (USD):", txtPres
                };

                int op = JOptionPane.showConfirmDialog(
                        VentanaPrincipalSistemaNuevo.this,
                        msg,
                        "Alta de Área",
                        JOptionPane.OK_CANCEL_OPTION);

                if (op == JOptionPane.OK_OPTION) {
                    String nombre = txtNombre.getText();
                    String desc = txtDesc.getText();
                    double pres;

                    try {
                        pres = Double.parseDouble(txtPres.getText());
                    } catch (NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(
                                VentanaPrincipalSistemaNuevo.this,
                                "Presupuesto inválido.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    boolean ok = sistema.altaArea(nombre, desc, pres);
                    if (sistema == null) {
                        sistema = new Sistema();
                    }
                    if (ok) {
                        JOptionPane.showMessageDialog(
                                VentanaPrincipalSistemaNuevo.this,
                                "Área creada correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(
                                VentanaPrincipalSistemaNuevo.this,
                                "No se pudo crear el área (nombre repetido o datos inválidos).",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });

        imnBajaAreas.setText("Baja");
        imnBajaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnBajaAreasActionPerformed(evt);
            }
        });
        bmnAreas.add(imnBajaAreas);

        imnModificacionAreas.setText("Modificacion");
        imnModificacionAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnModificacionAreasActionPerformed(evt);
            }
        });
        bmnAreas.add(imnModificacionAreas);

        imnMovimientoAreas.setText("Realizar Movimiento");
        bmnAreas.add(imnMovimientoAreas);

        barraMenu.add(bmnAreas);

        bmnManagers.setText("Managers");

        imnAltaManagers.setText("Alta");
        bmnManagers.add(imnAltaManagers);
        imnAltaManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (sistema == null)
                    sistema = new Sistema();

                javax.swing.JTextField txtNombre = new javax.swing.JTextField();
                javax.swing.JTextField txtCI = new javax.swing.JTextField();
                javax.swing.JTextField txtCel = new javax.swing.JTextField();
                javax.swing.JTextField txtAnt = new javax.swing.JTextField();

                Object[] msg = {
                        "Nombre:", txtNombre,
                        "CI:", txtCI,
                        "Celular (número):", txtCel,
                        "Antigüedad (años):", txtAnt
                };

                int op = JOptionPane.showConfirmDialog(
                        VentanaPrincipalSistemaNuevo.this,
                        msg,
                        "Alta de Manager",
                        JOptionPane.OK_CANCEL_OPTION);

                if (op == JOptionPane.OK_OPTION) {
                    String nombre = txtNombre.getText();
                    String ci = txtCI.getText();
                    int celular;
                    int antiguedad;

                    try {
                        celular = Integer.parseInt(txtCel.getText().trim());
                        antiguedad = Integer.parseInt(txtAnt.getText().trim());
                    } catch (NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(
                                VentanaPrincipalSistemaNuevo.this,
                                "Celular y Antigüedad deben ser numéricos.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    boolean ok = sistema.altaManager(nombre, ci, celular, antiguedad);
                    if (ok) {
                        JOptionPane.showMessageDialog(VentanaPrincipalSistemaNuevo.this,
                                "Manager creado correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(
                                VentanaPrincipalSistemaNuevo.this,
                                "No se pudo crear el manager (CI repetida o datos inválidos).",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });

        imnBajaManagers.setText("Baja");
        imnBajaManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnBajaManagersActionPerformed(evt);
            }
        });
        bmnManagers.add(imnBajaManagers);

        imnModificacionManagers.setText("Modificacion");
        bmnManagers.add(imnModificacionManagers);
        imnModificacionManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (sistema == null)
                    sistema = new Sistema();

                java.util.ArrayList<Manager> lista = sistema.listarManagersPorAntiguedadDesc();
                if (lista.isEmpty()) {
                    JOptionPane.showMessageDialog(
                            VentanaPrincipalSistemaNuevo.this,
                            "No hay managers registrados.",
                            "Info",
                            JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                String[] opciones = new String[lista.size()];
                int i = 0;
                while (i < lista.size()) {
                    Manager m = lista.get(i);
                    opciones[i] = m.getNombre() + " (" + m.getCi() + ")";
                    i++;
                }

                String sel = (String) JOptionPane.showInputDialog(
                        VentanaPrincipalSistemaNuevo.this,
                        "Seleccione el manager a modificar:",
                        "Modificar teléfono de Manager",
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        opciones,
                        opciones[0]);
                if (sel == null)
                    return;

                // Extraer la CI del string seleccionado: está entre paréntesis al final
                String ci = sel.substring(sel.indexOf('(') + 1, sel.indexOf(')'));

                String nuevoCel = JOptionPane.showInputDialog(
                        VentanaPrincipalSistemaNuevo.this,
                        "Nuevo celular (número):",
                        "");
                if (nuevoCel == null)
                    return;

                int celNum;
                try {
                    celNum = Integer.parseInt(nuevoCel.trim());
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(
                            VentanaPrincipalSistemaNuevo.this,
                            "El celular debe ser numérico.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                boolean ok = sistema.modificarTelefonoManager(ci, celNum);
                if (ok) {
                    JOptionPane.showMessageDialog(VentanaPrincipalSistemaNuevo.this, "Teléfono actualizado.");
                } else {
                    JOptionPane.showMessageDialog(
                            VentanaPrincipalSistemaNuevo.this,
                            "No se pudo actualizar el teléfono.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        barraMenu.add(bmnManagers);

        bmnEmpleados.setText("Empleados");

        imnAltaEmpleados.setText("Alta");
        bmnEmpleados.add(imnAltaEmpleados);
        imnAltaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                if (sistema == null)
                    sistema = new Sistema();

                // 1) Necesitamos al menos 1 manager y 1 área
                java.util.ArrayList<Manager> listaManagers = sistema.listarManagersPorAntiguedadDesc();
                java.util.ArrayList<Area> listaAreas = sistema.listarAreasOrdenadasPorNombre();

                if (listaManagers.isEmpty()) {
                    JOptionPane.showMessageDialog(
                            VentanaPrincipalSistemaNuevo.this,
                            "No hay managers cargados. Primero cree un manager.",
                            "Info",
                            JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                if (listaAreas.isEmpty()) {
                    JOptionPane.showMessageDialog(
                            VentanaPrincipalSistemaNuevo.this,
                            "No hay áreas cargadas. Primero cree un área.",
                            "Info",
                            JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                // 2) Campos de formulario
                javax.swing.JTextField txtNombre = new javax.swing.JTextField();
                javax.swing.JTextField txtCI = new javax.swing.JTextField();
                javax.swing.JTextField txtCel = new javax.swing.JTextField();
                javax.swing.JTextField txtSal = new javax.swing.JTextField();

                // CV (texto) en un área de texto con scroll
                javax.swing.JTextArea txtCV = new javax.swing.JTextArea(5, 20);
                javax.swing.JScrollPane spCV = new javax.swing.JScrollPane(txtCV);

                // Combos de selección (mostramos nombres, mapeamos por índice)
                String[] nombresManagers = new String[listaManagers.size()];
                int i = 0;
                while (i < listaManagers.size()) {
                    Manager m = listaManagers.get(i);
                    nombresManagers[i] = m.getNombre() + " (" + m.getCi() + ")";
                    i++;
                }
                javax.swing.JComboBox<String> cmbManager = new javax.swing.JComboBox<>(nombresManagers);

                String[] nombresAreas = new String[listaAreas.size()];
                int j = 0;
                while (j < listaAreas.size()) {
                    nombresAreas[j] = listaAreas.get(j).getNombre();
                    j++;
                }
                javax.swing.JComboBox<String> cmbArea = new javax.swing.JComboBox<>(nombresAreas);

                Object[] msg = {
                        "Nombre:", txtNombre,
                        "CI:", txtCI,
                        "Celular (número):", txtCel,
                        "Salario mensual (USD):", txtSal,
                        "Manager:", cmbManager,
                        "Área:", cmbArea,
                        "CV (texto):", spCV
                };

                int op = JOptionPane.showConfirmDialog(
                        VentanaPrincipalSistemaNuevo.this,
                        msg,
                        "Alta de Empleado",
                        JOptionPane.OK_CANCEL_OPTION);

                if (op == JOptionPane.OK_OPTION) {
                    String nombre = txtNombre.getText();
                    String ci = txtCI.getText();
                    String cvTxt = txtCV.getText();

                    int celular;
                    double salario;

                    try {
                        celular = Integer.parseInt(txtCel.getText().trim());
                        salario = Double.parseDouble(txtSal.getText().trim());
                    } catch (NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(
                                VentanaPrincipalSistemaNuevo.this,
                                "Celular debe ser entero y salario numérico.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    // Obtener Manager y Área seleccionados por índice
                    int idxM = cmbManager.getSelectedIndex();
                    int idxA = cmbArea.getSelectedIndex();
                    Manager mSeleleccionado = listaManagers.get(idxM);
                    Area aSeleleccionado = listaAreas.get(idxA);

                    boolean ok = sistema.altaEmpleado(nombre, ci, celular, cvTxt, salario, mSeleleccionado,
                            aSeleleccionado);
                    if (ok) {
                        JOptionPane.showMessageDialog(
                                VentanaPrincipalSistemaNuevo.this,
                                "Empleado creado correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(
                                VentanaPrincipalSistemaNuevo.this,
                                "No se pudo crear el empleado.\n" +
                                        "- Verifique CI única.\n" +
                                        "- Verifique presupuesto del área (12 meses).",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });

        barraMenu.add(bmnEmpleados);

        bmnReportes.setText("Reportes");

        imnReporteInteligente.setText("Reporte Inteligente");
        imnReporteInteligente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnReporteInteligenteActionPerformed(evt);
            }
        });
        bmnReportes.add(imnReporteInteligente);

        imnReporteEstadoAreas.setText("Reporte de Estado de Areas");
        bmnReportes.add(imnReporteEstadoAreas);

        imnReporteMovimientos.setText("Reporte de Movimientos");
        imnReporteMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnReporteMovimientosActionPerformed(evt);
            }
        });
        bmnReportes.add(imnReporteMovimientos);

        barraMenu.add(bmnReportes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imnBajaAreasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnBajaAreasActionPerformed
        ArrayList<Area> sinEmpleados = sistema.listarAreasSinEmpleados();
        if (sinEmpleados.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay áreas sin empleados para eliminar.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Armar combo de nombres
        String[] nombres = new String[sinEmpleados.size()];
        int i = 0;
        while (i < sinEmpleados.size()) {
            nombres[i] = sinEmpleados.get(i).getNombre();
            i++;
        }

        String sel = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione el área a eliminar:",
                "Baja de Área",
                JOptionPane.QUESTION_MESSAGE,
                null,
                nombres,
                nombres[0]);

        if (sel != null) {
            boolean ok = sistema.bajaArea(sel);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Área eliminada.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el área.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_imnBajaAreasActionPerformed

    private void imnModificacionAreasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnModificacionAreasActionPerformed
        ArrayList<Area> ordenadas = sistema.listarAreasOrdenadasPorNombre();
        if (ordenadas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay áreas registradas.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String[] nombres = new String[ordenadas.size()];
        int i = 0;
        while (i < ordenadas.size()) {
            nombres[i] = ordenadas.get(i).getNombre();
            i++;
        }

        String sel = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione el área a modificar:",
                "Modificar Área",
                JOptionPane.QUESTION_MESSAGE,
                null,
                nombres,
                nombres[0]);
        if (sel == null)
            return;

        String nuevaDesc = JOptionPane.showInputDialog(this, "Nueva descripción para " + sel + ":", "");
        if (nuevaDesc != null) {
            boolean ok = sistema.modificarDescripcionArea(sel, nuevaDesc);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Descripción actualizada.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la descripción.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_imnModificacionAreasActionPerformed

    private void imnBajaManagersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnBajaManagersActionPerformed
        if (sistema == null)
            sistema = new Sistema();

        java.util.ArrayList<Manager> lista = sistema.listarManagersPorAntiguedadDesc();
        java.util.ArrayList<Manager> soloSin = new java.util.ArrayList<Manager>();
        int i = 0;
        while (i < lista.size()) {
            if (lista.get(i).getEmpleadosACargo().isEmpty()) {
                soloSin.add(lista.get(i));
            }
            i++;
        }

        if (soloSin.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay managers sin empleados para eliminar.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String[] opciones = new String[soloSin.size()];
        int j = 0;
        while (j < soloSin.size()) {
            Manager m = soloSin.get(j);
            opciones[j] = m.getNombre() + " (" + m.getCi() + ")";
            j++;
        }

        String sel = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione el manager a eliminar:",
                "Baja de Manager",
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]);
        if (sel == null)
            return;

        String ci = sel.substring(sel.indexOf('(') + 1, sel.indexOf(')'));

        boolean ok = sistema.bajaManager(ci);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Manager eliminado.");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar (puede tener empleados a cargo).",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_imnBajaManagersActionPerformed

    private void imnReporteInteligenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnReporteInteligenteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_imnReporteInteligenteActionPerformed

    private void imnReporteMovimientosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imnReporteMovimientosActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_imnReporteMovimientosActionPerformed

    // =============================================
    // Listado y detalle de empleados
    // =============================================

    private void initUIListadoEmpleados() {
        pnlPrincipal.setLayout(new BorderLayout());

        // ----- Lista izquierda -----
        modeloListaEmpleados = new DefaultListModel<>();
        lstEmpleados = new JList<>(modeloListaEmpleados);
        lstEmpleados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        JScrollPane spLista = new JScrollPane(lstEmpleados);

        // ----- Panel de detalle derecha -----
        JPanel pnlDetalle = new JPanel(new GridLayout(0, 1, 5, 5));
        pnlDetalle.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        lblNombre = new JLabel("Nombre: -");
        lblCI = new JLabel("CI: -");
        lblCelular = new JLabel("Celular: -");
        lblSalario = new JLabel("Salario: -");
        lblManager = new JLabel("Manager: -");
        lblArea = new JLabel("Área: -");
        lblRutaCV = new JLabel("CV: -");

        pnlDetalle.add(lblNombre);
        pnlDetalle.add(lblCI);
        pnlDetalle.add(lblCelular);
        pnlDetalle.add(lblSalario);
        pnlDetalle.add(lblManager);
        pnlDetalle.add(lblArea);
        pnlDetalle.add(lblRutaCV);

        // ----- Split Pane -----
        JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, spLista, pnlDetalle);
        split.setDividerLocation(260); // ancho de la lista
        pnlPrincipal.add(split, BorderLayout.CENTER);

        // ----- Evento: selección de empleado -----
        lstEmpleados.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int idx = lstEmpleados.getSelectedIndex();
                if (idx >= 0 && cacheOrdenado != null && idx < cacheOrdenado.size()) {
                    mostrarDetalleEmpleado(cacheOrdenado.get(idx));
                }
            }
        });
    }

    private void refrescarListaEmpleados() {
        if (sistema == null)
            sistema = new Sistema();

        cacheOrdenado = sistema.listarEmpleadosPorSalarioAsc();
        modeloListaEmpleados.clear();

        int i = 0;
        while (i < cacheOrdenado.size()) {
            Empleado e = cacheOrdenado.get(i);
            String fila = String.format("$%.2f - %s (%s)", e.getSalarioMensual(), e.getNombre(), e.getCi());
            modeloListaEmpleados.addElement(fila);
            i++;
        }

        if (modeloListaEmpleados.isEmpty()) {
            limpiarDetalleEmpleado();
        } else {
            lstEmpleados.setSelectedIndex(0);
        }
    }

    private void mostrarDetalleEmpleado(Empleado e) {
        if (e == null) {
            limpiarDetalleEmpleado();
            return;
        }
        lblNombre.setText("Nombre: " + safe(e.getNombre()));
        lblCI.setText("CI: " + safe(e.getCi()));
        lblCelular.setText("Celular: " + e.getCelular());
        lblSalario.setText(String.format("Salario: $%.2f", e.getSalarioMensual()));

        Manager m = e.getManager();
        Area a = e.getArea();
        lblManager.setText("Manager: " + (m == null ? "-" : (safe(m.getNombre()) + " (" + safe(m.getCi()) + ")")));
        lblArea.setText("Área: " + (a == null ? "-" : safe(a.getNombre())));
        String ruta = (e.getRutaCV() == null || e.getRutaCV().isEmpty()) ? "-" : e.getRutaCV();
        lblRutaCV.setText("CV: " + ruta);
    }

    private void limpiarDetalleEmpleado() {
        lblNombre.setText("Nombre: -");
        lblCI.setText("CI: -");
        lblCelular.setText("Celular: -");
        lblSalario.setText("Salario: -");
        lblManager.setText("Manager: -");
        lblArea.setText("Área: -");
        lblRutaCV.setText("CV: -");
    }

    private String safe(String s) {
        return (s == null) ? "-" : s;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu bmnAreas;
    private javax.swing.JMenu bmnEmpleados;
    private javax.swing.JMenu bmnManagers;
    private javax.swing.JMenu bmnReportes;
    private javax.swing.JMenuItem imnAltaAreas;
    private javax.swing.JMenuItem imnAltaEmpleados;
    private javax.swing.JMenuItem imnAltaManagers;
    private javax.swing.JMenuItem imnBajaAreas;
    private javax.swing.JMenuItem imnBajaManagers;
    private javax.swing.JMenuItem imnModificacionAreas;
    private javax.swing.JMenuItem imnModificacionManagers;
    private javax.swing.JMenuItem imnMovimientoAreas;
    private javax.swing.JMenuItem imnReporteEstadoAreas;
    private javax.swing.JMenuItem imnReporteInteligente;
    private javax.swing.JMenuItem imnReporteMovimientos;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
